[alias]
bin = ["run", "--package", "cargo-bin", "--"]
pkg = ["run", "--bin", "build_pkgs", "--"]
api = ["run", "--bin", "api_tools", "--"]

# We need to enable dynamic linking for musl targets
# See https://github.com/rust-lang/rust/issues/59302#issue-422994250

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
