[project]
requires-python = ">=3.9,<4.0"
name = "algokit_transact"
version = "1.0.0a25"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "algokit_transact"
version = "0.1.0"
description = ""
packages = [
    { include = "algokit_transact" }
]
include = [
    { path = "algokit_transact/*.so", format = "wheel" },
    { path = "algokit_transact/*.dll", format = "wheel" },
    { path = "algokit_transact/*.dylib", format = "wheel" }
]

[tool.poetry.dependencies]
[tool.pytest.ini_options]
markers = [
  "group_generic_transaction_tests",
  "group_transaction_tests",
  "group_transaction_group_tests",
]

[tool.poetry.group.test.dependencies]
pynacl = ">=1.5.0,<2.0.0"
pytest = ">=7.4.4"

[tool.poetry.group.build.dependencies]
auditwheel = "^6.4.0"
patchelf = { version = "^0.17.2.2", markers = "sys_platform == 'linux'" }
